# Generated by Django 3.2.4 on 2021-06-08 15:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnails_urls',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnails',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
