# Generated by Django 3.2.4 on 2021-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210608_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
